name: deploy_to_play
on:
  push:
    branches:
      - work/release-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: secrets
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
        run: |
          echo $SERVICE_ACCOUNT_JSON > key/play-service-key.json
          echo $AI_API_KEY >> local.properties
      - name: build
        run: |
          ./gradlew publishToReleaseBundle
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}