name: deploy_to_play

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: secrets
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
        run: |
          mkdir key
          echo $SERVICE_ACCOUNT_JSON > key/play-service-key.json
          echo apiKey=$AI_API_KEY >> local.properties
          echo modelName=MODEL_NAME >> local.properties
          echo $GOOGLE_SERVICES_JSON > composeApp/src/release/google-services.json
      - name: build
        run: |
          ./gradlew publishReleaseBundle
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}